name: odoo push image
on:
  push:
   branches: [ main ]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USER_NAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USER_NAME}}/odoo16:latest

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOSTNAME}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          port: ${{secrets.PORT}}
          script: |
            sudo docker login -u ${{secrets.DOCKER_HUB_USER_NAME}} -p ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
            sudo docker stop odoo16
            sudo docker rm odoo16
            sudo docker volume rm odoo16-extra-addons
            sudo docker pull ${{secrets.DOCKER_HUB_USER_NAME}}/odoo16:latest
            sudo docker image ls -a
            sudo docker run --name odoo16 --network=host --mount source=odoo16-data,target=/var/lib/odoo --mount source=odoo16-extra-addons,target=/mnt/extra-addons -t -d  ${{secrets.DOCKER_HUB_USER_NAME}}/odoo16
            sudo docker system prune -a --volumes -f


